person_tags/urls.py
from django.conf.urls import url
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .models import PersonTag, PersonTaggedEntry, TagGroup
from .views import person_tag_create, person_tagged_entry_update

urlpatterns = [
    url(
        r"^$",
        ListView.as_view(
            queryset=PersonTaggedEntry.objects.default(),
            template_name="person_tags/persontaggedentry_list.html",
        ),
        name="persontag-person-list",
    ),
    url(
        r"^areas/$",
        ListView.as_view(queryset=TagGroup.objects.active()),
        name="persontag-taggroup-list",
    ),
    url(
        r"^areas/(?P<slug>[\w-]+)/$",
        DetailView.as_view(queryset=TagGroup.objects.active()),
        name="persontag-taggroup-detail",
    ),
    url(
        r"^interests/$",
        ListView.as_view(
            queryset=PersonTag.objects.tag_list(),
            template_name="person_tags/tag_list.html",
            context_object_name="tag_list",
        ),
        name="persontag-tag-list",
    ),
    url(
        r"^interests/(?P<slug>[\w-]+)/$",
        DetailView.as_view(
            queryset=PersonTag.objects.active(),
            template_name="person_tags/tag_detail.html",
            context_object_name="tag",
        ),
        name="persontag-tag-detail",
    ),
    url(
        r"^personal/(?P<slug>[\w-]+)/$",
        DetailView.as_view(
            queryset=PersonTag.objects.person_list(),
            template_name="person_tags/person_detail.html",
        ),
        name="persontag-person-detail",
    ),
    url(
        r"^personal/(?P<slug>[\w-]+)/update/$",
        person_tagged_entry_update,
        name="persontag-person-tagged-entry-update",
    ),
    url(
        r"^personal/(?P<slug>[\w-]+)/new-tag/$",
        person_tag_create,
        name="persontag-persontag-create",
    ),
    url(r"^tag/new/$", person_tag_create, name="persontag-persontag-create-general"),
]

person_tags/models.py
"""
Models for the person_tags.


Example Usages:
    * page of research interests.
"""
from __future__ import print_function, unicode_literals

import os

from django.db import models
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible
from people.models import Person

from . import conf

#######################################################################


class CustomQuerySetManager(models.Manager):
    """
    Custom Manager for an arbitrary model, just a wrapper for returning
    a custom QuerySet
    """

    queryset_class = models.query.QuerySet

    def get_queryset(self):
        """
        Return the custom QuerySet
        """
        return self.queryset_class(self.model)


class CustomQuerySet(models.query.QuerySet):
    """
    Custom QuerySet.
    """

    def active(self):
        """
        Returns only the active items in this queryset
        """
        return self.filter(active=True)


#######################################################################
#######################################################################
#######################################################################


class PersonTagQuerySet(CustomQuerySet):
    """
    Defines person_list and tag_list
    """

    def person_list(self):
        """
        Return a list of tagged people
        """
        pk_list = self.values_list("pk", flat=True)
        return PersonTaggedEntry.objects.get_people(tag__pk__in=pk_list)

    def tag_list(self):
        """
        Return a list of tags which are actually in use
        """
        pk_list = self.values_list("pk", flat=True)
        return PersonTaggedEntry.objects.get_tags(tag__pk__in=pk_list)


class PersonTagManager(CustomQuerySetManager):
    queryset_class = PersonTagQuerySet


PersonTagManager = PersonTagManager.from_queryset(PersonTagQuerySet)


@python_2_unicode_compatible
class PersonTag(models.Model):

    active = models.BooleanField(default=True)
    created = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name="creation time"
    )
    modified = models.DateTimeField(
        auto_now=True, editable=False, verbose_name="last modification time"
    )

    slug = models.SlugField(max_length=255, unique=True, verbose_name="URL fragment")
    tag = models.CharField(
        max_length=255,
        help_text="A word or short phrase (only a few words) is best. Do not use capitals except in proper names.",
    )

    objects = PersonTagManager()

    class Meta:
        ordering = ["tag"]
        base_manager_name = "objects"

    def __str__(self):
        return self.tag

    def get_absolute_url(self):
        if self.groups.count() == 1:
            return reverse(
                "persontag-taggroup-detail", kwargs={"slug": self.groups.get().slug}
            )
        else:
            return reverse("persontag-tag-detail", kwargs={"slug": self.slug})

    @property
    def groups(self):
        """
        Returns a queryset of groups that this tag belongs to.
        """
        return TagGroup.objects.filter(tags=self).active()


#######################################################################


class PersonTaggedEntryQuerySet(CustomQuerySet):
    def get_people(self, **kwargs):
        """
        Given a person tag, return the list of people who have that tag.
        """
        qs = self.filter(active=True, **kwargs)
        pk_list = qs.values_list("person", flat=True).distinct()
        # NB: DISTINCT required b/c directoryentry__active will
        #   cause people with multiple directory entries to occur
        #   multiple times.
        return Person.objects.filter(
            active=True,
            pk__in=pk_list,
            flags__slug="directory",
            directoryentry__active=True,
        ).distinct()

    def get_tags(self, **kwargs):
        """
        Given a person, return all associated tags.
        """
        qs = self.filter(active=True, **kwargs)
        pk_list = qs.values_list("tag", flat=True).distinct()
        return PersonTag.objects.filter(active=True, pk__in=pk_list)

    def default(self):
        """
        Get a default queryset
        """
        return self.filter(
            active=True,
            tag__active=True,
            person__active=True,
            person__flags__slug="directory",
        ).select_related("person", "tag")


class PersonTaggedEntryManager(CustomQuerySetManager):
    queryset_class = PersonTaggedEntryQuerySet


PersonTaggedEntryManager = PersonTaggedEntryManager.from_queryset(
    PersonTaggedEntryQuerySet
)


@python_2_unicode_compatible
class PersonTaggedEntry(models.Model):
    """
    Essentially managing the Many to many relationship manually, with
    optional ordering.
    """

    active = models.BooleanField(default=True)
    created = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name="creation time"
    )
    modified = models.DateTimeField(
        auto_now=True, editable=False, verbose_name="last modification time"
    )

    person = models.ForeignKey(
        Person,
        on_delete=models.CASCADE,
        limit_choices_to={"active": True, "flags__slug": "directory"},
    )
    tag = models.ForeignKey(
        PersonTag, on_delete=models.CASCADE, limit_choices_to={"active": True}
    )
    ordering = models.PositiveSmallIntegerField(default=10)

    objects = PersonTaggedEntryManager()

    class Meta:
        ordering = ["person", "ordering", "tag"]
        verbose_name_plural = "person tagged entries"
        unique_together = [["person", "tag"]]
        base_manager_name = "objects"

    def __str__(self):
        return "{}".format(self.tag)


#######################################################################


class TagGroupQuerySet(CustomQuerySet):
    """
    Custom QuerySet for TagGroups.
    """


class TagGroupManager(CustomQuerySetManager):
    queryset_class = TagGroupQuerySet


TagGroupManager = TagGroupManager.from_queryset(TagGroupQuerySet)


@python_2_unicode_compatible
class TagGroup(models.Model):
    """
    Class for tag groups
    """

    active = models.BooleanField(default=True)
    created = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name="creation time"
    )
    modified = models.DateTimeField(
        auto_now=True, editable=False, verbose_name="last modification time"
    )

    name = models.CharField(max_length=128)
    short_name = models.CharField(max_length=64, blank=True)
    slug = models.SlugField(max_length=32, unique=True, verbose_name="URL fragment")

    description = models.TextField(blank=True)

    tags = models.ManyToManyField(PersonTag, blank=True)

    objects = TagGroupManager()

    class Meta:
        ordering = ["name"]
        base_manager_name = "objects"

    def __str__(self):
        return self.short_name or self.name

    def get_absolute_url(self):
        """
        Return the url
        """
        return reverse("persontag-taggroup-detail", kwargs={"slug": self.slug})

    @property
    def people(self):
        """
        Return a queryset of people who have tags in this group.
        """
        return self.tags.person_list()
        tag_pk_list = self.tags.values_list("pk", flat=True)
        qs = PersonTaggedEntry.objects.filter(tag__pk__in=tag_pk_list)
        return qs.get_people()


#######################################################################


@python_2_unicode_compatible
class Asset(models.Model):
    """
    A file asset for a shout.
    """

    active = models.BooleanField(default=True)
    created = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name="creation time"
    )
    modified = models.DateTimeField(
        auto_now=True, editable=False, verbose_name="last modification time"
    )
    taggroup = models.ForeignKey(TagGroup, on_delete=models.CASCADE)
    file = models.FileField(
        upload_to=conf.get("upload_to"), storage=conf.get("storage")
    )
    description = models.CharField(max_length=250, blank=True)

    def get_absolute_url(self):
        return self.file.url

    get_absolute_url.short_description = "url"

    def __str__(self):
        name = os.path.basename(self.file.name)
        if self.description:
            name += ": " + self.description
        return name


###############################################################
#

person_tags/templates/person_tags/__base.html
{% extends 'directory/__base.html' %}

{# ########################################### #}

{% block page_content_body %}

{% block body_content %}
{% endblock %}


{% endblock %}

{# ########################################### #}

{% block app_breadcrumbs %}
    <span class="divider">&gt;</span>
    {% include './includes/app_breadcrumbs.html' %}
    {% block page_breadcrumbs %}
    {% endblock %}
{% endblock app_breadcrumbs %}

{# ########################################### #}

person_tags/templates/person_tags/person_detail.html
{% extends 'person_tags/__base.html' %}

{# ######################################################### #}

{% block head_title %}Tags for {{ object }}{% endblock %}
{% block body_title %}Tags for {{ object }}{% endblock %}

{# ######################################################### #}

{% block body_content %}

<ul>
    {% for entry in person.persontaggedentry_set.active %}
        <li>
            {{ entry }}
        </li>
    {% endfor %}
</ul>


{% endblock %}


{# ######################################################### #}

person_tags/templates/person_tags/person_list.html
{% extends 'person_tags/__base.html' %}

{% block head_title %}Faculty Research{% endblock %}
{% block body_title %}Faculty Research{% endblock %}

{% block body_content %}

<ul>
    {% for person in person_list %}
        {% with direntry=person.directoryentry_set.all.0 %}
            {% if direntry %}
                <li> <strong>{% if direntry.get_absolute_url %}<a href="{{ direntry.get_absolute_url }}">{% endif %}{{ person }}{% if direntry.get_absolute_url %}</a>{% endif %}</strong>:
                    {% for entry in person.persontaggedentry_set.active %}
                        {# <a href="{{ entry.tag.get_absolute_url }}">{{ entry }}</a>{% if not forloop.last %}, {% endif %} #}
                        {% if entry.tag.groups %}
                            <a href="{{ entry.tag.get_absolute_url }}">
                                {{ entry }}</a>{% if not forloop.last %}, {% endif %}
                        {% else %}
                            {{ entry }}{% if not forloop.last %}, {% endif %}
                        {% endif %}
                    {% endfor %}
            {% endif %}
        {% endwith %}
    {% endfor %}
</ul>


{% endblock %}

person_tags/templates/person_tags/persontag_form.html
{% extends 'person_tags/__base.html' %}

{# ######################################################### #}

{% block head_title %}{% if object %}Update {{ object }}{% else %}Create New Tag{% endif %}{% endblock %}
{% block body_title %}{% if object %}Update {{ object }}{% else %}Create New Tag{% endif %}{% endblock %}

{# ######################################################### #}

{% block html_head %}
{{ block.super }}
{{ form.media }}
{% endblock %}

{# right sidebar should be empty in twocol mode #}
{% block page_right_sidebar %}{% endblock %}
{% block page_main_classes %}col-lg-10{% endblock %}

{# ######################################################### #}

{% block body_content %}

{% if person.slug %}
    <p><strong>Current tags:</strong>
    <ul>
        {% for entry in person.persontaggedentry_set.active %}
            <li>
                {{ entry }}
            </li>
        {% endfor %}
    </ul>
    <p>

    <p>
        &rarr;
        <a href="{% url 'persontag-person-tagged-entry-update' slug=person.slug %}">
            Update my tags
        </a>
    </p>
{% endif %}

<form enctype="multipart/form-data" action="" method="post" class="form">{% csrf_token %}
    <div class="form-container">
        <table class="table-form">
            {% include 'includes/form.html' %}
            <tr class="submit-row">
                <td>
                    <input type="submit" value="Create" class="save-btn">
                </td>
            </tr>
        </table>
    </div>
</form>


{% endblock %}


{# ######################################################### #}

person_tags/templates/person_tags/persontaggedentry_form.html
{% extends 'person_tags/__base.html' %}

{# ######################################################### #}

{% block head_title %}Tags for {{ person }}{% endblock %}
{% block body_title %}Tags for {{ person }}{% endblock %}

{# ######################################################### #}

{% block html_head %}
{{ block.super }}
{{ form.media }}
{% endblock %}

{# right sidebar should be empty in twocol mode #}
{% block page_right_sidebar %}{% endblock %}
{% block page_main_classes %}col-lg-10{% endblock %}


{# ######################################################### #}

{% block body_content %}

<ul>
    {% for entry in person.persontaggedentry_set.active %}
        <li>
            {{ entry }}
        </li>
    {% endfor %}
</ul>

<p>
    &rarr;
    <a href="{% url 'persontag-persontag-create' slug=person.slug %}">
        Create new tag
    </a>
</p>

<h3>Manage tags</h3>


<form enctype="multipart/form-data" action="" method="post" class="form">{% csrf_token %}
    <div class="form-container">
        <table class="table-form">
            {% include 'includes/form.html' %}
        </table>
        <table class="table-form">
            {% include 'person_tags/includes/inline_tabular_formset.html' %}
        </table>
        <table class="table-form">
            <tr class="submit-row">
                <td>
                    <input type="submit" value="Update" class="save-btn">
                </td>
            </tr>
        </table>
    </div>
</form>


{% endblock %}


{# ######################################################### #}

person_tags/templates/person_tags/persontaggedentry_list.html
{% extends 'person_tags/__base.html' %}

{% block head_title %}Faculty Research{% endblock %}
{% block body_title %}Faculty Research{% endblock %}

{% block body_content %}

{% regroup object_list by person as person_list %}

<ul>
    {% for person in person_list %}
        {% with directory_list=person.grouper.directoryentry_set.active %}
            {% with type_slug_list=directory_list.type_slug_list %}
                {% if type_slug_list %}
                    <li>
                        <strong>
                            <a href="{{ person.grouper.get_absolute_url }}">
                                {{ person.grouper }}</a></strong>{% if 'academic-staff' not in type_slug_list %} ({{ directory_list.0.type }}){% endif %}:
                        {% for entry in person.list %}
                            {% if entry.tag.groups %}
                                <a href="{{ entry.tag.get_absolute_url }}">
                                    {{ entry }}</a>{% if not forloop.last %}, {% endif %}
                            {% else %}
                                {{ entry }}{% if not forloop.last %}, {% endif %}
                            {% endif %}
                        {% endfor %}
                    </li>
                {% endif %}
            {% endwith %}
        {% endwith %}
    {% endfor %}
</ul>


{% endblock %}

{# ########################################### #}

{% block page_breadcrumbs %}
    <span class="divider">&gt;</span>
    By person
{% endblock page_breadcrumbs %}

{# ########################################### #}

person_tags/templates/person_tags/tag_detail.html
{% extends 'person_tags/__base.html' %}

{% block head_title %}{{ tag|capfirst }}{% endblock %}
{% block body_title %}{{ tag|capfirst }}{% endblock %}

{% block body_content %}

{% if tag.persontaggedentry_set.active %}
    <p>
        The following people have this interest:
        <ul>
        {% for entry in tag.persontaggedentry_set.active %}
            {% with person=entry.person %}
                <li>
                    {% if person.get_absolute_url %}
                        <a href="{{ person.get_absolute_url }}">
                            {{ person }}
                        </a>
                    {% else %}
                            {{ person }}
                    {% endif %}
                </li>
            {% endwith %}
        {% endfor %}
        </ul>
    </p>
{% endif %}

{% with group_list=tag.groups.active %}
    {% if group_list %}
        <p>
            This interest belongs to these research areas:
            <ul>
                {% for group in group_list %}
                    <li>
                        <a href="{{ group.get_absolute_url }}">
                            {{ group }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </p>
    {% endif %}
{% endwith %}

{% endblock %}

person_tags/templates/person_tags/tag_list.html
{% extends 'person_tags/__base.html' %}

{% block head_title %}Research Interests{% endblock %}
{% block body_title %}Research Interests{% endblock %}

{% block body_content %}

<ul>
    {% for tag in tag_list %}
        {% with person_list=tag.persontaggedentry_set.active.get_people %}
            {% if person_list %}
                <li>
                    <strong><a href="{{ tag.get_absolute_url }}">{{ tag|capfirst }}</a></strong>:
                    {% for person in person_list %}
                        {% if person.active and person.directoryentry_set.active %}
                            {% if person.get_absolute_url %}
                                <a href="{{ person.get_absolute_url }}">
                                    {{ person }}{% if not forloop.last %}, {% endif %}
                                </a>
                            {% else %}
                                    {{ person }}{% if not forloop.last %}, {% endif %}
                            {% endif %}
                        {% endif %}
                     {% endfor %}
                 </li>
             {% endif %}
         {% endwith %}
    {% endfor %}
</ul>


{% endblock %}

{# ########################################### #}

{% block page_breadcrumbs %}
    <span class="divider">&gt;</span>
    Interests
{% endblock page_breadcrumbs %}

{# ########################################### #}

person_tags/templates/person_tags/taggroup_detail.html
{% extends 'person_tags/__base.html' %}
{% load markup %}

{% block head_title %}{{ taggroup.name }}{% endblock %}
{% block body_title %}{{ taggroup.name }}{% endblock %}

{% block body_content %}

{{ taggroup.description|restructuredtext }}

{% if taggroup.people %}
    <p>
        {{ taggroup.people|pluralize:"This person is,These people are" }}
        involved in this research area:
        <ul class="simple">
            {% for person in taggroup.people %}
                {% with directory_list=person.directoryentry_set.active %}
                    {% with type_slug_list=directory_list.type_slug_list %}
                        {% if type_slug_list %}
                            <li>
                                <a href="{{ person.get_absolute_url }}">
                                    {{ person }}
                                </a>
                                {% if 'faculty' not in type_slug_list %}
                                    ({{ directory_list.0.type }})
                                {% endif %}
                            </li>
                        {% endif %}
                    {% endwith %}
                {% endwith %}
            {% endfor %}
        </ul>
    </p>
{% endif %}

{% include './includes/taggroup_detail_post.html' %}

{% endblock %}

{# ########################################### #}

{% block page_breadcrumbs %}
    <span class="divider">&gt;</span>
    {{ taggroup }}
{% endblock page_breadcrumbs %}

{# ########################################### #}

person_tags/templates/person_tags/taggroup_list.html
{% extends 'person_tags/__base.html' %}
{% load markup %}

{% block head_title %}Research Areas{% endblock %}
{% block body_title %}Research Areas{% endblock %}

{% block body_content %}

The Department has active research in the following main domains.
Click links below or to the left to find out more about a given domain,
including faculty members and students involved, publications, etc.


{% for taggroup in taggroup_list %}
    <h2>
        <a href="{{ taggroup.get_absolute_url }}">
            {{ taggroup.name }}
        </a>
    </h2>
    {{ taggroup.description|restructuredtext }}

{% endfor %}


{% endblock %}