people/urls.py
"""
Url patterns for the people application, primarly to be used
for verifying email
"""
from django.conf.urls import url

from . import views
from .models import EmailConfirmation
from .views import admin as views_admin

urlpatterns = [
    url(r"^$", views.profile_detail, name="people-person-detail"),
    url(
        r"^verify-me/(?P<pk>\d+)/$",
        views.request_confirmation_email,
        name="people-verify-email",
    ),
    url(
        r"^confirm-email/" + EmailConfirmation.VERIFIED + "/$",
        views.already_verified,
        name="people-email-already-verified",
    ),
    url(
        r"^confirm-email/(?P<slug>[\w-]+)/$",
        views.confirm_email,
        name="people-email-confirmed",
    ),
    # administrative functions -- always restricted
    url(r"^_list/$", views_admin.person_list, name="people-admin-person-list"),
    url(r"^_new/$", views_admin.person_create, name="people-admin-person-create"),
    url(
        r"^_update/(?P<pk>[\d]+)/$",
        views_admin.person_update,
        name="people-admin-person-update",
    ),
    url(
        r"^_detail/(?P<pk>[\d]+)/$",
        views_admin.person_detail,
        name="people-admin-person-detail",
    ),
]

people/models.py
"""
Models for contacts.  A contact is a person and all of their associated information,
e.g., phone numbers, addresses, etc.
"""
###############
from __future__ import print_function, unicode_literals

###############
import datetime
import re
from importlib import import_module

from autoslug.fields import AutoSlugField
from directory import PhoneNumberField, PostalCodeField, RegionField
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.contrib.sites.models import Site
from django.core import validators
from django.core.mail import EmailMessage
from django.db import models
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible

from . import conf, handlers
from .managers import (
    DEFAULT_CONFIRM_BODY_TEMPLATE,
    DEFAULT_CONFIRM_SUBJECT_TEMPLATE,
    BaseContactInfoManager,
    EmailConfirmationManager,
    PersonFlagManager,
    PersonManager,
)
from .querysets import PersonKeyQuerySet, PersonKeyValueQuerySet

#######################################################################

PERSON_PERMALINK = conf.get("permalink")

#######################################################################


class PeopleBaseModel(models.Model):
    """
    An abstract base class.
    """

    active = models.BooleanField(default=True)
    created = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name="creation time"
    )
    modified = models.DateTimeField(
        auto_now=True, editable=False, verbose_name="last modification time"
    )

    class Meta:
        abstract = True


#######################################################################


@python_2_unicode_compatible
class PersonFlag(PeopleBaseModel):
    """
    Flags for differentating people.
    Typically these are used to filter Person choices as FK in other apps.

    Examples: student, advisor, committee member, graduate student,
        in directory, etc.
    """

    slug = AutoSlugField(max_length=64, populate_from="verbose_name", unique=True)
    verbose_name = models.CharField(max_length=64)

    objects = PersonFlagManager()

    class Meta:
        ordering = ["verbose_name"]
        base_manager_name = "objects"

    def __str__(self):
        return self.verbose_name


#######################################################################


@python_2_unicode_compatible
class Person(PeopleBaseModel):
    """
    A person.  Any known person goes here.
    """

    flags = models.ManyToManyField(PersonFlag, blank=True)

    cn = models.CharField(
        max_length=100,
        verbose_name="common name",
        blank=True,
        help_text="""This is how the person's name will appear in the site.
                                    Leave this blank to use given name + family name.
                                    """,
    )
    sn = models.CharField(
        max_length=64,
        verbose_name="family name",
        help_text="This will determine how this person gets sorted in lists or people.",
    )
    given_name = models.CharField(
        max_length=64,
        help_text="Typically how the person prefers to be addressed, informally.",
    )
    sync_name = models.BooleanField(
        default=True,
        verbose_name="sync name with user",
        help_text="Synchronize name information with corresponding user model",
    )
    title = models.CharField(
        max_length=64, blank=True, help_text="A personal title or job title."
    )
    company = models.CharField(
        max_length=64,
        blank=True,
        help_text="The company this person if affiliated with.",
    )
    birthday = models.DateField(
        blank=True,
        null=True,
        help_text="If this is not required, just leave this blank.",
    )

    username = models.CharField(
        max_length=64,
        unique=True,
        db_index=True,
        null=True,
        blank=True,
        help_text="Username on the local system, if the person has one. 64 characters or fewer. Letters, numbers and "
        "@/./+/-/_ characters",
        validators=[
            validators.RegexValidator(
                re.compile(r"^[\w.@+-]+$"), "Enter a valid username.", "invalid"
            )
        ],
    )
    slug = AutoSlugField(
        unique=True,
        db_index=True,
        null=True,
        blank=True,
        populate_from=conf.get("person:slug:populate_from"),
        verbose_name="URL fragment",
    )

    note = models.TextField(blank=True)

    objects = PersonManager()

    class Meta:
        ordering = ["sn", "given_name"]
        verbose_name_plural = "people"
        base_manager_name = "objects"

    def __str__(self):
        return self.cn

    def clean(self, *args, **kwargs):
        """
        This bit of magic is to allow unique but empty for undefined or unrequired UserIDs.
        Source: http://www.hoboes.com/Mimsy/hacks/django-empty-strings/ [2009-Oct-20]
        """
        if self.username == "":
            self.username = None
        if self.slug == "":
            self.slug = None
        if self.cn == "":
            self.cn = self.given_name + " " + self.sn
        super(Person, self).clean(*args, **kwargs)

    if PERSON_PERMALINK is not None:

        def get_absolute_url(self):
            """
            This bit of magic is to allow a completely plugable system for
            personal pages.
            Note that personal pages are not guaranteed to exist when a person
            exists; even when they have a slug.
            """
            if isinstance(PERSON_PERMALINK, (tuple, list)):
                view_name, arg_callable_string = PERSON_PERMALINK
                if callable(arg_callable_string):
                    arg_callable = arg_callable_string
                else:
                    mod_name, f_name = arg_callable_string.rsplit(".", 1)
                    arg_callable = getattr(import_module(mod_name), f_name)
                args = arg_callable(self)
                if args is not None:
                    return reverse(view_name, args=args)
            elif callable(PERSON_PERMALINK):
                return PERSON_PERMALINK(self)
            elif isinstance(PERSON_PERMALINK, str):
                mod_name, f_name = arg_callable_string.rsplit(".", 1)
                f = getattr(import_module(mod_name), f_name)
                return f(self)
            return None

    ##################
    ## The following methods deal with changing a person's flags
    ##################

    def add_flag_by_name(self, slug, verbose_name=None):
        """
        Add the named PersonFlag to this person.  Create if necessary.

        Verbose name and verbose name plural, if given, are defaults only.
        """
        if not verbose_name:
            verbose_name = slug

        obj, created = PersonFlag.objects.get_or_create(
            slug=slug, defaults={"verbose_name": verbose_name}
        )

        if obj not in self.flags.all():
            self.flags.add(obj)

    def remove_flag_by_name(self, slug):
        """
        Remove the named PersonFlag from this person.
        """
        try:
            obj = PersonFlag.objects.get(slug=slug)
        except PersonFlag.DoesNotExist:
            return  # not a valid flag slug
        self.flags.remove(obj)

    def has_flag(self, slug):
        """
        Returns true if the user has the flag, False otherwise.
        """
        return self.flags.filter(slug=slug).count() > 0

    ######################
    def get_user(self):
        """
        Retrieve the corresponding user object, if it exists
        """
        return get_user_model().objects.get(username=self.username)

    ######################
    ## The following utility methods deal with setting and retrieving
    ## contact information.
    ######################

    def add_contact_info(self, type_, ci_type_slug, **data):
        ci_type, ci_flag = ContactInfoType.objects.get_or_create(
            slug=ci_type_slug,
            defaults={
                "verbose_name": ci_type_slug.title(),
                "verbose_name_plural": ci_type_slug.title(),
            },
        )
        preferred = data.pop("preferred", False)
        public = data.pop("public", False)
        verified = data.pop("verified", False)
        # data['type'] = ci_type

        data["person"] = self
        # if it already exists; but has a different type (or preferred,
        # public, or verified); that's fine. (particularly: email)
        obj, flag = type_.objects.get_or_create(
            **data,
            defaults={
                "type": ci_type,
                "preferred": preferred,
                "public": public,
                "verified": verified,
            }
        )
        if preferred:  # clear any other preferreds on this type_, for this person
            type_.objects.filter(person=self, type=ci_type).exclude(pk=obj.pk).update(
                preferred=False
            )
            if not obj.preferred:
                obj.preferred = True
                obj.save()
        return obj

    def add_email(self, address, type_slug, preferred=False, **kwargs):
        kwargs["preferred"] = preferred
        return self.add_contact_info(EmailAddress, type_slug, address=address, **kwargs)

    def add_phone(self, number, type_slug, preferred=False):
        return self.add_contact_info(
            PhoneNumber, type_slug, number=number, preferred=preferred
        )

    def add_address(self, data, type_slug, preferred=False):
        return self.add_contact_info(
            StreetAddress, type_slug, preferred=preferred, **data
        )

    def get_contact_info(self, type_, ci_type_slug=None):
        """
        This method *only* returns items that are public.
        """
        qs = type_.objects.filter(active=True, person=self, public=True)
        if ci_type_slug is not None:

people/templates/people/__base.html
{% extends "site_base.html" %}

{# ########################################### #}

{% block html_head %}
{{ block.super }}
{% block html_head_people_extra %}
{% endblock %}
{% endblock html_head %}

{# ########################################### #}

{% block page_title %}{% block head_title %}HEAD TITLE{% endblock %}{% endblock %}

{# ########################################### #}

{% block page_content_header %}{% block body_title %}INSERT TITLE{% endblock %}{% endblock %}

{% block page_content_body %}

{% block body_content %}
INSERT CONTENT
{% endblock %}

{% block people_extra_content %}{% endblock %}

{% endblock %}

{# ########################################### #}

{% block breadcrumbs %}
    {{ block.super }}
    {% block app_breadcrumbs %}
        <span class="divider">&gt;</span>
        {% include './includes/app_breadcrumbs.html' %}
        {% block page_breadcrumbs %}
        {% endblock %}
    {% endblock app_breadcrumbs %}
{% endblock %}

{# ########################################### #}

people/templates/people/emailaddress_detail.html
{% extends "people/__base.html" %}

{# ########################################### #}

{% block head_title %}Email confirmation{% endblock %}
{% block body_title %}Email confirmation{% endblock %}

{# ########################################### #}


{% block body_content %}

<p>
Please check your email at <tt>{{ emailaddress }}</tt>
for your confirmation message.
</p>

<p>
<strong>Please note</strong>: you may need to check your spam mailbox for this email message.
</p>

{% endblock %}


{# ########################################### #}

people/templates/people/emailconfirmation_already_verified.html
{% extends "people/__base.html" %}

{# ########################################### #}

{% block head_title %}Email Verified{% endblock %}
{% block body_title %}Email Verified{% endblock %}

{# ########################################### #}


{% block body_content %}

<p>
You have already verified your email address.
</p>

{% endblock %}


{# ########################################### #}

people/templates/people/emailconfirmation_detail.html
{% extends "people/__base.html" %}

{# ########################################### #}

{% block head_title %}Email Verified{% endblock %}
{% block body_title %}Email Verified{% endblock %}

{# ########################################### #}


{% block body_content %}

<p>
You have verified your email address <tt>{{ emailconfirmation.email }}</tt>.
</p>

{% if emailconfirmation.redirect_url %}
<p>
    Please
    <a href="{{ emailconfirmation.redirect_url }}">
        click this link
    </a>
    to go back to what you were doing.
</p>
{% endif %}
{% endblock %}


{# ########################################### #}

people/templates/people/pagination.html
{% extends 'site_pagination.html' %}

people/templates/people/person_detail.html
{% extends "people/__base.html" %}

{# ########################################### #}

{% block head_title %}Person Detail{% endblock %}
{% block body_title %}Person Detail{% endblock %}

{# ########################################### #}

{% block page_breadcrumbs %}
    <a href="{% url 'people-admin-person-list' %}">
        Person list
    </a>
    <span class="divider">&gt;</span>
    {{ object }}
{% endblock page_breadcrumbs %}

{# ########################################### #}

{% block body_content %}

<ul class="pagenav">
    <li>
        <a href="{% url 'people-admin-person-update' pk=person.pk %}">
            Edit this person record
        </a>
    </li>
</ul>

{% include 'people/includes/person_info.html' with third_person=1 %}

{% endblock %}


{# ########################################### #}

people/templates/people/person_form.html
{% extends "people/__base.html" %}

{# ########################################### #}

{% block head_title %}{% if object.pk %}Update{% else %}Create{%endif %} Person{% endblock %}
{% block body_title %}{% if object.pk %}Update{% else %}Create{%endif %} Person{% endblock %}

{# ########################################### #}

{# right sidebar should be empty in twocol mode #}
{% block page_right_sidebar %}{% endblock %}
{% block page_main_classes %}col-lg-10{% endblock %}

{# ########################################### #}

{% block html_head %}
{{ block.super }}
{{ form.media }}
<!-- form media just above. -->
{% endblock %}

{# ########################################### #}

{% block page_breadcrumbs %}
    <a href="{% url 'people-admin-person-list' %}">
        Person list
    </a>
    <span class="divider">&gt;</span>
    {% if object.pk %}
        <a href="{% url 'people-admin-person-detail' pk=person.pk %}">
            {{ person }}
        </a>
        <span class="divider">&gt;</span>
        Update
    {% else %}
        Create
    {% endif %}
{% endblock page_breadcrumbs %}

{# ########################################### #}

{% block body_content %}

    <form enctype="multipart/form-data" action="" method="post" class="form">{% csrf_token %}
        <table class="table-form">
            <tr><th>{{ form.subform_title }}</th></tr>
            {% include 'includes/form.html' with visual_break=True %}
            {% for f in form.extra_forms %}
                <tr class="table-form-row-even"></tr>
                <tr><th>{{ f.subform_title }}</th></tr>
                {% include 'includes/form.html' with form=f visual_break=True %}
            {% endfor %}
            <tr class="table-form-row-even"></tr>
            <tr class="submit-row">
                <td>
                    <input type="submit" value="{% if object.pk %}Update{% else %}Create{%endif %}">
                </td>
            </tr>
        </table>
    </form>


{% endblock %}


{# ########################################### #}

people/templates/people/person_list.html
{% extends "people/__base.html" %}

{# ########################################### #}

{% block head_title %}Person List{% endblock %}
{% block body_title %}Person List{% endblock %}

{# ########################################### #}

{% block page_breadcrumbs %}
    {% if request.GET.q %}
        <a href="{% url 'people-admin-person-list' %}">
            Person list
        </a>
        <span class="divider">&gt;</span>
        Search results
    {% else %}
        Person list
    {% endif %}
{% endblock page_breadcrumbs %}

{# ########################################### #}


{% block body_content %}

<ul class="pagenav">
    {% url 'people-admin-person-create' as link_url %}
    {% if link_url and perms.people.add_person %}
        <li>
            <a href="{{ link_url }}">
                Create a new person record
            </a>
        </li>
    {% endif %}
</ul>

    <p>
        <form action="{% url 'people-admin-person-list' %}">
            Search:
            <input id="id_search" type="text" name="q" maxlength="100" />
            <input type="submit" value="Search">
        </form>
    </p>

    {% if request.GET.q %}
        <h3>
            Search results for &ldquo;<tt>{{ request.GET.q }}</tt>&rdquo;
        </h3>
    {% endif %}

    <ul>
    {% for person in person_list %}
        <li>
            <a href="{% url 'people-admin-person-detail' pk=person.pk %}">
                {{ person }}
            </a>
        </li>
    {% endfor %}
    </ul>

    {% if is_paginated %}
        {% url 'people-admin-person-list' as paginated_base_url %}
        {% include 'people/pagination.html' with paginated_base_url=paginated_base_url object_name="people" %}
    {% endif %}

{% endblock %}

{# ########################################### #}

people/templates/people/person_profile.html
{% extends "people/__base.html" %}
{% load static %}

{# ########################################### #}

{% block head_title %}Personal Profile{% endblock %}
{% block body_title %}Personal Profile{% endblock %}

{# ########################################### #}

{% block html_head_people_extra %}
    <script src="{% static 'js/clipboard.min.js' %}"></script>
{% endblock %}

{# ########################################### #}

{% block page_breadcrumbs %}
    {{ block.super }}
    Profile
{% endblock %}


{# ########################################### #}

{% block body_content %}

<ul class="pagenav">
{% block content_pagenav %}
{% url 'people-admin-person-list' as link_url %}
{% if link_url and perms.people.change_person %}
    <li>
        <a href="{{ link_url }}">
            Person list
        </a>
    </li>
{% endif %}
{% endblock %}
</ul>

{% include 'people/includes/person_info.html' with third_person=0 %}

{% endblock %}


{# ########################################### #}

{% block people_extra_content %}
    <script>
        new Clipboard('.copy-link-btn');
    </script>
{% endblock %}

{# ########################################### #}